services:
  mongo:
    image: mongo
    container_name: mongo
    expose:
      - 27017

  redis:
    image: redis:7.0
    container_name: redis
    expose:
      - 6379

  go-server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile  
    container_name: backend
    environment:
      - MONGO_URL=mongodb://localhost:27017
      - REDIS_ADDRESS=redis:6379
    ports:
      - 8080:8080



